### ISSUE TITLE
Could you add some good tests for this SDK?

### ISSUE THREAD

**Issue by adamthedeveloper** [wepay/Ruby-SDK#1]
Hi Guys,

  Right now wepay-rails uses HTTParty for communications with the wepay api. I'd like to change that and use your SDK instead. We are starting a major testing effort on the wepay-rails gem and I was hoping that you guys could write some around your SDK that can call your service in a real way vs. stubbing out some responses. This would help us to ensure that our code is good as well.

Thanks in advance,

Adam (wepay-rails)

**Comment by skyzyx** [comment]
It's taken way, way, way too long, but they're here in master. Will go out as part of `0.3.0`.
