### ISSUE TITLE
Undefined method '+@' thrown in oauth2_authorize_url

### ISSUE THREAD

**Issue by jakehockey10** [wepay/Ruby-SDK#13]
Hello,

I just wanted to let you know of an error I was receiving when calling the `oauth2_authorize_url` method that is part of the `Client` class.  This might be due to having certain versions of certain files, but if I made the following changes:

![screenshot of changes](https://cloud.githubusercontent.com/assets/1821383/7606458/241b8946-f916-11e4-83cd-673d72883376.png)

Things seemed to go back to normal for this call.  I got the idea from this page:

![plusatgooglesearch](https://cloud.githubusercontent.com/assets/1821383/7606482/5f7e9fb4-f916-11e4-8217-bfe8d5b75ee8.png)

and the reason I'm giving you a screenshot instead of a link to that page is because I think the site is actually down now, but google let me view a cached copy of the page that didn't have any styling and some characters missing.  Here is [THAT link](http://webcache.googleusercontent.com/search?q=cache:http://greghaygood.com/2008/06/16/undefined-method-for-string).  Hope this helps.  Thanks for the gem.

**Comment by jakehockey10** [comment]
I'm sorry, I completely forgot, I meant to give my `Gemfile` as well to help replicate the issue:

```ruby
source 'https://rubygems.org'
ruby '2.1.2'

gem 'rails'
gem 'bootstrap-sass'
gem 'sass-rails', '>= 3.2'
gem 'autoprefixer-rails'
gem 'bootstrap_form'
gem 'bcrypt-ruby'
gem 'faker', '1.1.2'
gem 'will_paginate'
gem 'bootstrap-will_paginate'
gem 'state_machines-activerecord'
gem 'twitter_cldr'
gem 'pg'

gem 'figaro'
gem 'jquery-turbolinks'

gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'mail_form'
gem 'ransack'
gem 'momentjs-rails'
gem 'bootstrap3-datetimepicker-rails'
gem 'date_validator'
gem 'gmaps4rails'
gem 'geocoder'
gem 'underscore-rails'
gem 'bootstrap-select-rails'
gem 'fullcalendar-rails'
gem 'wepay'
gem 'omnicontacts', '~> 0.3.5', git: 'git://github.com/Diego81/omnicontacts.git'
gem 'rails4-autocomplete'
gem 'paperclip'
gem 'aws-s3'
gem 'aws-sdk', '< 2.0'
gem 'mail'
gem 'mailboxer', github: 'lacco/mailboxer' #Use this branch until Foreigner is no longer used in Mailboxer.  Incompatible with Rails 4.2.  See https://bithub.com/mailboxer/mailboxer/issues/316
gem 'bootstrap_tokenfield_rails'
gem 'font-awesome-rails'

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'rspec-rails', '2.14.0'
  gem 'guard-rspec', '2.5.0'
  gem 'meta_request'
end

group :test do
  gem 'selenium-webdriver', '2.35.1'
  gem 'capybara', '2.1.0'
  gem 'factory_girl_rails', '4.2.1'
end

group :doc do
  gem 'sdoc', '0.3.20', require: false
end

group :production do
  gem 'rails_12factor'
end

```

**Comment by skyzyx** [comment]
/me thinks Ruby is weird.

Fix applied. Gem updated. Go nuts. :smile:

**Comment by jakehockey10** [comment]
:+1: Thanks :)
